name: Export workflow from a private repository

on:
  workflow_run:
    workflows:
      # The name of the workflow(s) that triggers the export
      - "My workflow"
    types: [completed]

jobs:
  otel-export-private:
    runs-on: ubuntu-latest
    # Permissions can be set on a per-job basis or at the top level
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    steps:
      - uses: actions/checkout@v4
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: "CHANGE_ME"
          otlpHeaders: "CHANGE_ME"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
